version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "1"
    ports:
      - "3000:3000"
    command: npm start